export const REQUEST = 'REQUEST';
export const SUCCESS = 'SUCCESS';
export const FAILURE = 'FAILURE';

export const ACCESS_TOKEN = 'ACCESS_TOKEN';

export const USER_REQUEST = 'USER_REQUEST';
export const USER_SUCCESS = 'USER_SUCCESS';
export const USER_FAILURE = 'USER_FAILURE';

export const BOARD_LIST_REQUEST = 'BOARD_LIST_REQUEST';
export const BOARD_LIST_SUCCESS = 'BOARD_LIST_SUCCESS';
export const BOARD_LIST_FAILURE = 'BOARD_LIST_FAILURE';

export const BOARD_DETAIL_REQUEST = 'BOARD_DETAIL_REQUEST';
export const BOARD_DETAIL_SUCCESS = 'BOARD_DETAIL_SUCCESS';
export const BOARD_DETAIL_FAILURE = 'BOARD_DETAIL_FAILURE';
